# ./docker-compose.yml

services:
  redis:
    image: redis:alpine
    # Add persistence: ensures task queue survives restarts
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  backend:
    build: ./backend
    ports:
      - "4131:8000"
    volumes:
      - ./data:/app/data           # audio + SQLite
      - ./backend:/app             # hot-reload code in dev
    env_file: [.env]
    depends_on: [redis]

  celeryworker:
    build: ./backend              # same image as backend
    command: celery -A app.worker.celery_app worker -l info -c 1
    volumes:
      - whisper-cache:/root/.cache # ← HuggingFace + CTranslate2 cache
      - ./data:/app/data           # DB + audio
      - ./backend:/app             # code
    env_file: [.env]
    depends_on: [redis]
    # Add grace period: allows worker to finish its current task
    stop_grace_period: 1m

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "4132:80"
    env_file: [.env]
    depends_on: [backend]

volumes:
  whisper-cache: {}               # named volume persists model weights
  # Define the named volume for Redis data
  redis-data: {}