# docker-compose.yml

version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "4131:8000"
    volumes:
      - ./data:/app/data         # audio + sqlite
      - ./backend:/app           # For hot-reloading code in dev
    env_file:
      - .env

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "4132:80"
    env_file:
      - .env
    depends_on:
      - backend
