# ./docker-compose.yml

services:
  redis:
    image: redis:alpine
    # Add persistence: ensures task queue survives restarts
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  backend:
    build: ./backend
    command: >
      sh -c "python /app/utils/add_meeting_metadata_columns.py &&
             python /app/utils/add_suggestion_column.py &&
             python /app/utils/add_summary_length_column.py &&
             python /app/utils/add_feedback_uniqueness.py &&
             python /app/utils/add_feedback_status_column.py &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "4131:8000"
    volumes:
      - ./data:/app/data
      - ./backend:/app
    env_file: [.env]
    depends_on: [redis]

  celeryworker:
    build: ./backend
    command: >
      sh -c "python /app/utils/add_meeting_metadata_columns.py &&
             python /app/utils/add_suggestion_column.py &&
             python /app/utils/add_summary_length_column.py &&
             python /app/utils/add_feedback_uniqueness.py &&
             python /app/utils/add_feedback_status_column.py &&
             celery -A app.worker.celery_app worker -B -l info -c 1"
    volumes:
      - whisper-cache:/root/.cache
      - ./data:/app/data
      - ./backend:/app
    env_file: [.env]
    depends_on: [redis]
    # Add grace period: allows worker to finish its current task
    stop_grace_period: 1m

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "4132:80"
    env_file: [.env]
    depends_on: [backend]

volumes:
  whisper-cache: {}               # named volume persists model weights
  # Define the named volume for Redis data
  redis-data: {}

