version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "4131:8000"
    volumes:
      - ./data:/app/data         # audio + sqlite
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "4132:80"
    depends_on:
      - backend

