# docker-compose.yml

version: "3.8"

services:
  redis:
    image: redis:alpine

  backend:
    build: ./backend
    ports:
      - "4131:8000"
    volumes:
      - ./data:/app/data         # audio + sqlite
      - ./backend:/app           # For hot-reloading code in dev
    env_file:
      - .env
    depends_on:
      - redis

  rqworker:
    build: ./backend
    command: >
      rq worker transcription --url redis://redis:6379/0
    volumes:
      - ./data:/app/data
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - redis

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "4132:80"
    env_file:
      - .env
    depends_on:
      - backend
