# ./docker-compose.yml

services:
  redis:
    image: redis:alpine
    # Add persistence: ensures task queue survives restarts
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  migration:
    build: ./backend
    command: >
      sh -c "echo 'Running DB migrations...' &&
             python /app/utils/remove_feedback_uniqueness.py &&
             python /app/utils/add_meeting_metadata_columns.py &&
             python /app/utils/add_suggestion_column.py &&
             python /app/utils/add_summary_length_column.py &&
             python /app/utils/add_feedback_status_column.py &&
             python /app/utils/add_summary_language_columns.py &&
             python /app/utils/add_context_column.py &&
             echo 'Migrations complete.'"
    volumes:
      - ./data:/app/data
      - ./backend:/app
    env_file: [.env]
    depends_on:
      - redis

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "4131:8000"
    volumes:
      - ./data:/app/data
      - ./backend:/app
    env_file: [.env]
    depends_on:
      migration:
        condition: service_completed_successfully

  celeryworker:
    build: ./backend
    command: celery -A app.worker.celery_app worker -B -l info -c 1
    volumes:
      - whisper-cache:/root/.cache
      - ./data:/app/data
      - ./backend:/app
    env_file: [.env]
    depends_on:
      migration:
        condition: service_completed_successfully
    # Add grace period: allows worker to finish its current task
    stop_grace_period: 1m

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "4132:80"
    env_file: [.env]
    depends_on: [backend]

volumes:
  whisper-cache: {}               # named volume persists model weights
  # Define the named volume for Redis data
  redis-data: {}



