services:
  redis:
    image: redis:alpine

  backend:
    build: ./backend
    ports:
      - "4131:8000"
    volumes:
      - ./data:/app/data           # audio + SQLite
      - ./backend:/app             # hot-reload code in dev
    env_file: [.env]
    depends_on: [redis]

  celeryworker:
    build: ./backend              # same image as backend
    command: celery -A app.worker.celery_app worker -l info -c 1
    volumes:
      - whisper-cache:/root/.cache # ← HuggingFace + CTranslate2 cache
      - ./data:/app/data           # DB + audio
      - ./backend:/app             # code
    env_file: [.env]
    depends_on: [redis]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "4132:80"
    env_file: [.env]
    depends_on: [backend]

volumes:
  whisper-cache: {}               # named volume persists model weights
