#!/usr/bin/env python3
"""
utils/add_local_summary_table.py
────────────────────────────────────────────────────────
Creates the `localsummaryrun` table: one row per summary generated by an
LLM running in the user's browser, kept alongside the Claude summary so the
two can be compared (see app/models.py::LocalSummaryRun).

`create_all` only ever adds missing tables, so this is idempotent and safe
to re-run — which is what the migration runner does on every boot.
"""

import logging
import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
if str(ROOT_DIR) not in sys.path:
    sys.path.append(str(ROOT_DIR))

from migration_helper import ensure_database_exists

logging.basicConfig(level=logging.INFO, format="[%(levelname)s] %(message)s")
logger = logging.getLogger("migration")


def run_migration():
    _db_path, engine = ensure_database_exists()

    # Importing the models registers every table with SQLModel's metadata.
    from app.models import LocalSummaryRun  # noqa: F401
    from sqlmodel import SQLModel

    SQLModel.metadata.create_all(engine)
    logger.info("localsummaryrun table present.")


if __name__ == "__main__":
    run_migration()
