import datetime as dt
import uuid
from typing import List, Optional

from sqlmodel import Field, SQLModel


# ──────────────────────────────────────────────────────────────────────────────
# Data-models
# ──────────────────────────────────────────────────────────────────────────────
class Meeting(SQLModel, table=True):
    """
    Main DB table for a recorded meeting.
    """

    id: uuid.UUID | None = Field(default_factory=uuid.uuid4, primary_key=True)
    title: str
    started_at: dt.datetime = Field(default_factory=dt.datetime.utcnow)
    last_activity: dt.datetime = Field(default_factory=dt.datetime.utcnow)
    expected_chunks: int | None = None
    received_chunks: int = 0
    final_received: bool = False
    transcript_text: Optional[str] = None
    summary_markdown: Optional[str] = None
    done: bool = False
    summary_task_queued: bool = False
    # --- NEW COLUMNS ---
    word_count: int | None = None
    duration_seconds: int | None = None
    user_agent: str | None = None
    summary_length: str = Field(default="narrative")
    summary_language_mode: str = Field(default="auto")
    summary_custom_language: str | None = None
    context: str | None = None
    timezone: str | None = None
    # Which post-meeting stage is running: 'transcribing' | 'diarizing' |
    # 'summarizing' | None. Drives the frontend's progress text; None once
    # `done` is set.
    processing_stage: str | None = None
    # How many stages this particular run has, so the UI can say "step 2 of 3".
    # A fresh recording skips transcription (already done live) and has 2;
    # reprocessing an old meeting re-transcribes first and has 3.
    processing_total: int | None = None
    # Distinct speakers found by diarization; None if it did not run.
    speaker_count: int | None = None
    # True once the meeting has been through the diarization pipeline at
    # all — even if it found nothing, e.g. a silent recording. Meetings
    # predating the feature are False, which is what the "find speakers"
    # hint keys off. Absence of Speaker labels is NOT the same thing.
    diarization_attempted: bool = False
    # Experimental: transcription and diarization ran in the user's browser
    # (Parakeet + pyannote/campplus via ONNX Runtime Web). The server still
    # stores the audio and chunk texts as usual, but must neither transcribe
    # nor diarize — it only summarizes the transcript the client hands over.
    client_processing: bool = False
    # JSON blob of what the browser measured: model download size/time,
    # transcription speed, diarization time, backend used. Purely informative.
    client_stats: str | None = None


class MeetingChunk(SQLModel, table=True):
    """
    Stores metadata & transcription text for every uploaded chunk.
    """

    id: int | None = Field(default=None, primary_key=True)
    meeting_id: uuid.UUID = Field(foreign_key="meeting.id")
    chunk_index: int
    path: str
    text: Optional[str] = None
    # Whisper's segment timings for this chunk, as JSON [{start,end,text}].
    # Times are chunk-relative; diarization converts them to absolute using
    # the offsets it measures when decoding the audio.
    segments_json: Optional[str] = None
    # True decoded length. Chunks are NOT reliably 30s, so this is the only
    # trustworthy basis for absolute positions and meeting duration.
    audio_seconds: Optional[float] = None


class Feedback(SQLModel, table=True):
    """
    Stores user feedback on summaries. Uniqueness for standard feedback types
    is enforced in the application layer, not by the database, to allow
    multiple 'feature_suggestion' entries for the same meeting.
    """

    id: int | None = Field(default=None, primary_key=True)
    meeting_id: uuid.UUID = Field(foreign_key="meeting.id")
    feedback_type: str
    suggestion_text: Optional[str] = None
    created_at: dt.datetime = Field(default_factory=dt.datetime.utcnow)
    status: str = Field(default="new")  # 'new', 'done', etc.


class LocalSummaryRun(SQLModel, table=True):
    """
    Experimental: one summary generated by an LLM running in the user's
    browser (Qwen3.5 via transformers.js/WebGPU), kept next to — never
    instead of — the Claude summary on `Meeting.summary_markdown`.

    Rows exist to answer one question: is an on-device model good enough?
    So each one stores the output, the settings it was produced under, what
    the hardware was, how long every phase took, and the user's own verdict
    against the cloud summary. That makes the table an eval set that grows
    as the feature is used, queryable straight out of sqlite.
    """

    id: int | None = Field(default=None, primary_key=True)
    meeting_id: uuid.UUID = Field(foreign_key="meeting.id", index=True)
    created_at: dt.datetime = Field(default_factory=dt.datetime.utcnow)

    # ── What produced it ──────────────────────────────────────────────────
    # Hugging Face repo id, e.g. "onnx-community/Qwen3.5-4B-ONNX-OPT".
    model: str
    dtype: str
    device: str  # 'webgpu' | 'wasm'
    thinking: bool = False
    # The summary mode and language the prompt asked for, copied from the
    # meeting at generation time so a later settings change cannot silently
    # invalidate the comparison.
    summary_length: str
    target_language: str | None = None
    markdown: str

    # ── What it cost ──────────────────────────────────────────────────────
    prompt_chars: int | None = None
    prompt_tokens: int | None = None
    output_tokens: int | None = None
    download_bytes: int | None = None
    download_ms: int | None = None
    # True when every model file came from the browser cache (no network).
    cached: bool = False
    load_ms: int | None = None
    # Time to the first streamed token: the prefill of a whole transcript,
    # which is the number that decides whether this is usable at all.
    prefill_ms: int | None = None
    decode_ms: int | None = None
    total_ms: int | None = None
    # Stopped early because it hit max_new_tokens rather than an EOS token,
    # so the markdown is probably truncated.
    truncated: bool = False

    # ── Where it ran ──────────────────────────────────────────────────────
    # JSON: {cores, memory_gb, gpu_vendor, gpu_architecture, mobile, ...}
    device_info: str | None = None
    user_agent: str | None = None

    # ── The verdict ───────────────────────────────────────────────────────
    # 'cloud' | 'tie' | 'local' | None (not yet judged).
    verdict: str | None = None
    verdict_note: str | None = None


class LocalSummaryRunCreate(SQLModel):
    """An on-device summary the browser just finished, with its measurements."""

    model: str
    dtype: str
    device: str
    thinking: bool = False
    summary_length: str
    target_language: str | None = None
    markdown: str = Field(max_length=500_000)
    prompt_chars: int | None = None
    prompt_tokens: int | None = None
    output_tokens: int | None = None
    download_bytes: int | None = None
    download_ms: int | None = None
    cached: bool = False
    load_ms: int | None = None
    prefill_ms: int | None = None
    decode_ms: int | None = None
    total_ms: int | None = None
    truncated: bool = False
    device_info: dict | None = None


class LocalSummaryVerdictUpdate(SQLModel):
    """Which summary the user judged better, and why."""

    verdict: str | None = None
    verdict_note: str | None = None


class SummaryPromptOut(SQLModel):
    """
    The exact prompt the server would send Claude for this meeting, so the
    on-device model can be given the same one.
    """

    prompt: str
    target_language: str
    summary_length: str
    prompt_chars: int


class MeetingCreate(SQLModel):
    """
    Payload for creating a meeting from the frontend.
    """

    title: str
    expected_chunks: int | None = None
    summary_length: str | None = None
    summary_language_mode: str | None = None
    summary_custom_language: str | None = None
    context: str | None = None
    timezone: str | None = None
    client_processing: bool = False


class FeedbackCreate(SQLModel):
    """
    Payload for submitting feedback. Can be a type or a suggestion.
    """

    meeting_id: uuid.UUID
    feedback_type: str
    suggestion_text: Optional[str] = None


class FeedbackDelete(SQLModel):
    """
    Payload for deleting a feedback item.
    """

    meeting_id: uuid.UUID
    feedback_type: str


class FeedbackStatusUpdate(SQLModel):
    """
    Payload for updating the status of a feedback item.
    """

    status: str


class MeetingStatus(SQLModel):
    """
    What we send back to the frontend for status polling:
    """

    id: uuid.UUID
    title: str
    started_at: dt.datetime
    summary_markdown: Optional[str]
    transcript_text: Optional[str]
    done: bool
    received_chunks: int
    expected_chunks: Optional[int]
    transcribed_chunks: int
    summary_length: str
    summary_language_mode: str
    summary_custom_language: str | None = None
    context: str | None = None
    timezone: str | None = None
    processing_stage: str | None = None
    processing_total: int | None = None
    speaker_count: int | None = None
    diarization_attempted: bool = False
    # True when the original audio survives, so speakers can still be identified.
    can_rediarize: bool = False
    client_processing: bool = False
    client_stats: str | None = None
    feedback: list[str] = []  # List of submitted feedback types


class ChunkSegment(SQLModel):
    start: float
    end: float
    text: str


class ChunkTranscriptUpdate(SQLModel):
    """One chunk transcribed in the browser (on-device mode)."""

    text: str
    segments: list[ChunkSegment] = []
    audio_seconds: float | None = None


class ClientFinalizePayload(SQLModel):
    """
    The browser finished transcribing and diarizing: here is the labelled
    transcript, summarize it. `client_stats` is free-form JSON for the UI.
    """

    transcript: str
    speaker_count: int | None = None
    duration_seconds: int | None = None
    client_stats: dict | None = None


class MeetingTitleUpdate(SQLModel):
    """
    Payload for updating a meeting's title.
    """

    title: str


class MeetingContextUpdate(SQLModel):
    """Payload for updating a meeting's context."""

    context: str


class MeetingMeta(SQLModel):
    """
    Slimmed-down meeting model for history lists.
    """

    id: uuid.UUID
    title: str
    started_at: dt.datetime
    status: str  # "pending" | "complete"


class MeetingSyncRequest(SQLModel):
    """
    Payload for the sync endpoint, containing the list of
    meeting IDs the client is aware of.
    """

    ids: list[uuid.UUID]


class RegeneratePayload(SQLModel):
    """
    Payload for the regenerate endpoint, allowing a new
    summary length to be specified.
    """

    summary_length: str | None = None
    summary_language_mode: str | None = None
    summary_custom_language: str | None = None
    context: str | None = None


class MeetingConfigUpdate(SQLModel):
    """
    Payload for updating a meeting's configuration, like summary length.
    """

    summary_length: Optional[str] = None
    summary_language_mode: Optional[str] = None
    summary_custom_language: Optional[str] = None


class MeetingTranslatePayload(SQLModel):
    """Payload for translating a meeting."""

    target_language: str
    language_mode: str


class MeetingSection(SQLModel, table=True):
    """
    Individual sections within a meeting summary that can be customized.
    """

    id: Optional[int] = Field(default=None, primary_key=True)
    meeting_id: uuid.UUID = Field(foreign_key="meeting.id")
    section_type: str  # "default_summary", "timeline", "key_points", "feedback_suggestions", "metrics", "custom"
    title: str
    content: Optional[str] = None
    position: int
    created_at: dt.datetime = Field(default_factory=dt.datetime.utcnow)
    updated_at: dt.datetime = Field(default_factory=dt.datetime.utcnow)
    is_generating: bool = Field(default=False)
    # Enhanced context fields
    start_timestamp: Optional[int] = None  # Seconds from meeting start
    end_timestamp: Optional[int] = None    # Seconds from meeting start
    speakers: Optional[str] = None         # JSON array of speaker names when available
    extra_data: Optional[str] = None       # JSON for additional context (tags, confidence, etc.)


class SectionCreate(SQLModel):
    """
    Payload for creating a new section.
    """

    meeting_id: uuid.UUID
    section_type: str
    title: str
    position: int


class SectionUpdate(SQLModel):
    """
    Payload for updating a section.
    """

    title: Optional[str] = None
    content: Optional[str] = None
    position: Optional[int] = None


class SectionReorder(SQLModel):
    """
    Payload for reordering sections.
    """

    sections: List[dict]  # List of {id: int, position: int}


class SummaryUpdate(SQLModel):
    """
    Payload for updating a meeting's summary markdown directly.
    """

    content: str = Field(max_length=500_000)
